apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: next-app
profiles:
  - name: dev-unstable
    build:
      artifacts:
        - image: my-image
    deploy:
      kubectl:
        manifests:
          kustomize:
            paths:
              - ./overlays/dev-unstable/
              - ./base/
