# apiVersion: skaffold/v2beta16
# kind: Config
# metadata:
#   name: next-app
# profiles:
#   - name: dev-unstable
#     manifests:
#       kustomize:
#         paths:
#           - ./overlays/dev-unstable
#           - ./base
# deploy:
#   kubectl: {}
apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: next-app
profiles:
  - name: dev-unstable
    # build:
    #   artifacts:
    #     - image: gcr.io/your-project-id/next-app:${SKAFFOLD_PROFILE}
    deploy:
      kubectl:
        manifests:
          kustomize:
            paths:
              - ./overlays/dev-unstable/
              - ./base/
