apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: next
  name: next
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: IMAGE_REPLACE_OVERLAY
        name: next
        
