apiVersion: apps/v1
kind: Deployment
metadata:
  name: next
  labels:
    app: next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next
  strategy: {}
  template:
    metadata:
      labels:
        app: next
    spec:
      containers:
      - name: next
        image: IMAGE_REPLACE
        imagePullPolicy: "Always"
        resources: {}
        ports:
        - containerPort: 3000

status: {}
